apiVersion: v1
kind: Secret
metadata:
  name: mashinato-bot-secret
  namespace: car-api
type: Opaque
stringData:
  BOT_TOKEN: "REPLACE_ME"
  OAUTH_CLIENT_ID: "mashinato-bot"
  OAUTH_CLIENT_SECRET: "REPLACE_ME"
  WEBHOOK_SECRET: "REPLACE_ME"
