apiVersion: v1
kind: Service
metadata:
  name: mashinato-bot
  namespace: mashinato-bot
  labels:
    app: mashinato-bot
spec:
  type: ClusterIP
  selector:
    app: mashinato-bot
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
